### ISSUE TITLE
feature request: Improve math counter display

### ISSUE THREAD

**Issue by Rushaway** [srcdslab/sm-plugin-EntWatch#16]
Instead of having [x/xx] format for math counter, it will be easier to understand if we display the percent used of left from the item
Ex: Flamethrower[15%]: {playername}

![image](https://github.com/user-attachments/assets/223db143-1e67-46f2-945f-9ce679966c58)

**Comment by Rushaway** [comment]
What do you think of this @notkoen ?

**Comment by notkoen** [comment]
I don't like using percentages to display counters. Some maps use `math_counter` for item cooldowns (e.g. salikawood and fiendlord keep). Being able to see the specific amount of fuel left is much better. Also, the second number is based on `m_flMax`, or the `Max` keyvalue of the counter. You can use a stripper to fix that display so it shows `[15/15]`.

**Comment by maximee-leroyy** [comment]
yeah i agree with koen
